import { motion, useInView } from 'framer-motion';
import { useRef, useState } from 'react';

const EASE = [0.16, 1, 0.3, 1] as const;

const tabs = [
  {
    label: 'SDK',
    code: `import { getOptimizedUrl, isNotionImageUrl } from 'notion-image-cdn';

const notionUrl =
  'https://prod-files-secure.s3.us-west-2.amazonaws.com/abc/def/photo.jpg?X-Amz-...';

if (isNotionImageUrl(notionUrl)) {
  const cdnUrl = getOptimizedUrl(notionUrl, {
    cdnBaseUrl: 'https://cdn.example.com',
    width: 800,
    format: 'webp',
    quality: 85,
  });
  // → https://cdn.example.com/img/abc/def/photo.jpg?w=800&fmt=webp&q=85
}`,
  },
  {
    label: 'React',
    code: `import { NotionImage } from 'notion-image-cdn/react';

<NotionImage
  src={notionUrl}
  cdnBaseUrl="https://cdn.example.com"
  alt="Blog header"
  width={1200}
  format="webp"
  quality={85}
  loading="lazy"
  className="w-full"
/>`,
  },
  {
    label: 'Plugin',
    code: `import { createNotionImagePlugin } from 'notion-image-cdn';

const rewrite = createNotionImagePlugin({
  cdnBaseUrl: 'https://cdn.example.com',
  defaultFormat: 'webp',
  defaultQuality: 85,
  defaultWidth: 1200,
});

// Use with react-markdown, MDX, or any renderer:
const components = {
  img: ({ src, alt }) => <img src={rewrite(src)} alt={alt} loading="lazy" />,
};`,
  },
  {
    label: 'API',
    code: `# Proxy endpoint — pass any Notion S3 URL
GET /api/v1/proxy?url=<encoded-notion-url>&w=800&fmt=webp&q=85

# Clean permanent URL (generated by SDK)
GET /img/:workspaceId/:blockId/:filename?w=800&fmt=webp

# Response headers
X-Cache: HIT | MISS
X-Cache-Tier: L2_EDGE | L3_PERSISTENT | ORIGIN
X-Original-Size: 2048000
X-Optimized-Size: 156000`,
  },
];

export function CodeShowcase() {
  const [activeTab, setActiveTab] = useState(0);
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: '-80px' });

  return (
    <section ref={ref} className="w-full py-24 lg:py-32">
      <div className="w-full max-w-7xl mx-auto px-6 lg:px-8">
        {/* Two-column layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
          {/* Left — heading */}
          <div className="lg:col-span-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={isInView ? { opacity: 1 } : {}}
              transition={{ duration: 0.5, delay: 0.1 }}
            >
              <span className="font-mono text-[11px] tracking-[0.3em] uppercase text-cobalt mb-5 block">
                Developer Experience
              </span>
              <h2 className="font-serif text-[clamp(2rem,4vw,3rem)] leading-[1.1] tracking-tighter text-foreground mb-4">
                Drop in. It just works.
              </h2>
              <p className="font-sans text-sm text-muted-foreground leading-relaxed">
                Four integration paths — pick the one that fits your stack. All produce the same
                permanent CDN URL.
              </p>
            </motion.div>
          </div>

          {/* Right — tabbed code block */}
          <div className="lg:col-span-8">
            <motion.div
              initial={{ opacity: 0, scale: 0.99 }}
              animate={isInView ? { opacity: 1, scale: 1 } : {}}
              transition={{ duration: 0.6, ease: EASE, delay: 0.3 }}
            >
              {/* Tab bar */}
              <div className="flex border-b border-white/[0.06]">
                {tabs.map((tab, i) => (
                  <button
                    key={i}
                    onClick={() => setActiveTab(i)}
                    className={`px-5 py-3 font-mono text-xs tracking-wider transition-colors duration-200 relative ${
                      activeTab === i
                        ? 'text-foreground'
                        : 'text-muted-foreground hover:text-foreground/70'
                    }`}
                  >
                    {tab.label}
                    {activeTab === i && (
                      <motion.div
                        layoutId="tab-indicator"
                        className="absolute bottom-0 left-0 right-0 h-px bg-cobalt"
                        transition={{ duration: 0.25, ease: EASE }}
                      />
                    )}
                  </button>
                ))}
              </div>

              {/* Code content */}
              <div className="border border-t-0 border-white/[0.06] bg-white/[0.02] p-6 overflow-x-auto custom-scrollbar">
                <motion.pre
                  key={activeTab}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.25 }}
                >
                  <code className="font-mono text-[13px] text-foreground/70 leading-relaxed whitespace-pre">
                    {tabs[activeTab].code}
                  </code>
                </motion.pre>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
}
